name: Regenerate MATLAB bindings
# This action regenerates the MATLAB bindings for CasADi
# Inspired from:
#  * https://github.com/robotology/yarp-matlab-bindings/blob/master/.github/workflows/regenerate-matlab-bindings.yml
#  * https://github.com/robotology/idyntree/blob/master/.github/workflows/regenerate-matlab-bindings.yml

on:
  workflow_dispatch:
  pull_request:

jobs:
    regenerate-matlab-bindings:
        name: "Regenerate MATLAB bindings"
        runs-on: [ubuntu-20.04]
        container:
        # Use Ubuntu Bionic as the https://github.com/casadi/casadi/wiki/matlab suggest to use GCC 7
          image: ubuntu:bionic
        steps:
        - uses: actions/checkout@v2

        - name: Install dependencies via apt
          run: |
            # Install CasADi dependencies
            apt-get update -y
            apt-get upgrade -y
            # From https://github.com/casadi/casadi/wiki/InstallationLinux
            apt-get install -y build-essential gcc g++ gfortran git cmake liblapack-dev pkg-config coinor-libipopt-dev liboctave-dev --install-recommends
            # From https://github.com/swig/swig/wiki/Getting-Started
            apt-get install -y libpcre3-dev autoconf automake libtool bison --install-recommends

            
        # From https://github.com/casadi/casadi/wiki/matlab
        - name: Install SWIG for that supports MATLAB required by CasADi
          run: |
            cd ..
            git clone https://github.com/jaeandersson/swig
            cd swig
            git checkout matlab-customdoc
            sh autogen.sh
            ./configure --with-matlab
            make 
            make install

        - name: Verify which SWIG and gcc is found 
          run: |
            which swig
            swig --help
            which gcc
            gcc --version
          

        - name: Configure and compile CasADi
          run: |
            # Clone casadi from a given tag
            git clone https://github.com/dic-iit/casadi.git
            cd casadi
            git checkout 3.5.5.3
            # Compile casadi and generate MATLAB bindings
            mkdir build
            cd build
            ccmake -DWITH_IPOPT:BOOL=ON -DWITH_OCTAVE:BOOL=ON -DWITH_EXAMPLES:BOOL=OFF -DINCLUDE_PREFIX:PATH=include -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_PREFIX:PATH=lib/cmake/casadi -DLIB_PREFIX:PATH=lib -DBIN_PREFIX:PATH=bin ..
            make install
            echo "Print content of build directory:"
            ls -R

        - name: Check local changes due to bindings generation
          run: |
            git status
            
        - name: Create Pull Request
          id: cpr
          uses: peter-evans/create-pull-request@v3
          with:
            commit-message: 'update matlab bindings'
            committer: GitHub <noreply@github.com>
            branch: regenerate-matlab-bindings
            delete-branch: true
            title: 'update matlab bindings'
            body: |
              This is a PR that regenerated the MATLAB/Octave CasADi bindings.
                            
              For more info, check the documentation of this repo. 

        - name: Check outputs
          run: |
            echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
            echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
